aropixel_admin_highlight:
  resource: |
    alias: aropixel.highlight
    section: admin
    path: highlight-products
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: aropixel_admin_highlight_products
    vars:
        all:
            subheader: aropixel.ui.highlight_products
            templates:
              form: "@AropixelSyliusHighLightProductsPlugin/Admin/HighLightProduct/Form/_form.html.twig"
        index:
            icon: 'file image outline'
  type: sylius.resource
