stof_doctrine_extensions:
  default_locale: fr_FR
  orm:
    default:
      timestampable: true


sylius_resource:
  resources:
    aropixel.highlight:
      driver: doctrine/orm
      classes:
        model: Aropixel\SyliusHighLightProductsPlugin\Entity\HighLight
        interface: Aropixel\SyliusHighLightProductsPlugin\Entity\HighLightInterface
        form: Aropixel\SyliusHighLightProductsPlugin\Form\Type\HighLightType
    aropixel.highlight_product:
      driver: doctrine/orm
      classes:
        model: Aropixel\SyliusHighLightProductsPlugin\Entity\HighLightProduct
        interface: Aropixel\SyliusHighLightProductsPlugin\Entity\HighLightProductInterface
        form: Aropixel\SyliusHighLightProductsPlugin\Form\Type\HighLightProductType

sylius_grid:
  grids:
    aropixel_admin_highlight_products:
      driver:
        name: doctrine/orm
        options:
          class: Aropixel\SyliusHighLightProductsPlugin\Entity\HighLight
      fields:
        title:
          type: string
          label: aropixel.highlight_products.title
        code:
          type: string
          label: aropixel.highlight_products.code
        enabled:
          type: twig
          label: sylius.ui.enabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete

sylius_ui:
  events:
    sylius.admin.layout.javascripts:
      blocks:
        aropixel_admin_highlight_scripts:
          template: "@AropixelSyliusHighLightProductsPlugin/Admin/_scripts.html.twig"
          priority: 100

    sylius.admin.layout.stylesheets:
      blocks:
        aropixel_admin_highlight_styles:
          template: "@AropixelSyliusHighLightProductsPlugin/Admin/_styles.html.twig"
          priority: 100
